//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 04:10:21 PM EST 
//


package org.apromore.pnml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for netToolspecificType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="netToolspecificType">
 *   &lt;complexContent>
 *     &lt;extension base="{pnml.apromore.org}toolspecificType">
 *       &lt;sequence>
 *         &lt;element name="bounds" type="{pnml.apromore.org}graphicsSimpleType" minOccurs="0"/>
 *         &lt;element name="treeWidth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="verticalLayout" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="resources" type="{pnml.apromore.org}resourcesType" minOccurs="0"/>
 *         &lt;element name="simulations" type="{pnml.apromore.org}simulationsType" minOccurs="0"/>
 *         &lt;element ref="{pnml.apromore.org}partnerLinks" minOccurs="0"/>
 *         &lt;element ref="{pnml.apromore.org}variables" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "netToolspecificType", propOrder = {
    "bounds",
    "treeWidth",
    "verticalLayout",
    "resources",
    "simulations",
    "partnerLinks",
    "variables"
})
public class NetToolspecificType
    extends ToolspecificType
{

    protected GraphicsSimpleType bounds;
    protected Integer treeWidth;
    protected Boolean verticalLayout;
    protected ResourcesType resources;
    protected SimulationsType simulations;
    protected TPartnerLinks partnerLinks;
    protected TVariables variables;

    /**
     * Gets the value of the bounds property.
     * 
     * @return
     *     possible object is
     *     {@link GraphicsSimpleType }
     *     
     */
    public GraphicsSimpleType getBounds() {
        return bounds;
    }

    /**
     * Sets the value of the bounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphicsSimpleType }
     *     
     */
    public void setBounds(GraphicsSimpleType value) {
        this.bounds = value;
    }

    /**
     * Gets the value of the treeWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTreeWidth() {
        return treeWidth;
    }

    /**
     * Sets the value of the treeWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTreeWidth(Integer value) {
        this.treeWidth = value;
    }

    /**
     * Gets the value of the verticalLayout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerticalLayout() {
        return verticalLayout;
    }

    /**
     * Sets the value of the verticalLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerticalLayout(Boolean value) {
        this.verticalLayout = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcesType }
     *     
     */
    public ResourcesType getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcesType }
     *     
     */
    public void setResources(ResourcesType value) {
        this.resources = value;
    }

    /**
     * Gets the value of the simulations property.
     * 
     * @return
     *     possible object is
     *     {@link SimulationsType }
     *     
     */
    public SimulationsType getSimulations() {
        return simulations;
    }

    /**
     * Sets the value of the simulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulationsType }
     *     
     */
    public void setSimulations(SimulationsType value) {
        this.simulations = value;
    }

    /**
     * Gets the value of the partnerLinks property.
     * 
     * @return
     *     possible object is
     *     {@link TPartnerLinks }
     *     
     */
    public TPartnerLinks getPartnerLinks() {
        return partnerLinks;
    }

    /**
     * Sets the value of the partnerLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPartnerLinks }
     *     
     */
    public void setPartnerLinks(TPartnerLinks value) {
        this.partnerLinks = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link TVariables }
     *     
     */
    public TVariables getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVariables }
     *     
     */
    public void setVariables(TVariables value) {
        this.variables = value;
    }

}
