/* Generated By:JJTree: Do not edit this line. ASTconceptSet.java */

package org.prom5.analysis.ltlchecker.parser;

public class ASTconceptSet extends SimpleNode {
  public ASTconceptSet(int id) {
    super(id);
  }

  public ASTconceptSet(LTLParser p, int id) {
    super(p, id);
  }

}
