//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 04:10:32 PM EST 
//


package org.apromore.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ClusteringSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClusteringSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumClusters" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minClusterSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxClusterSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minAvgFragmentSize" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="maxAvgFragmentSize" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="minBCR" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="maxBCR" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClusteringSummaryType", propOrder = {
    "numClusters",
    "minClusterSize",
    "maxClusterSize",
    "minAvgFragmentSize",
    "maxAvgFragmentSize",
    "minBCR",
    "maxBCR"
})
public class ClusteringSummaryType
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "NumClusters")
    protected int numClusters;
    protected int minClusterSize;
    protected int maxClusterSize;
    protected float minAvgFragmentSize;
    protected float maxAvgFragmentSize;
    protected double minBCR;
    protected double maxBCR;

    /**
     * Gets the value of the numClusters property.
     * 
     */
    public int getNumClusters() {
        return numClusters;
    }

    /**
     * Sets the value of the numClusters property.
     * 
     */
    public void setNumClusters(int value) {
        this.numClusters = value;
    }

    /**
     * Gets the value of the minClusterSize property.
     * 
     */
    public int getMinClusterSize() {
        return minClusterSize;
    }

    /**
     * Sets the value of the minClusterSize property.
     * 
     */
    public void setMinClusterSize(int value) {
        this.minClusterSize = value;
    }

    /**
     * Gets the value of the maxClusterSize property.
     * 
     */
    public int getMaxClusterSize() {
        return maxClusterSize;
    }

    /**
     * Sets the value of the maxClusterSize property.
     * 
     */
    public void setMaxClusterSize(int value) {
        this.maxClusterSize = value;
    }

    /**
     * Gets the value of the minAvgFragmentSize property.
     * 
     */
    public float getMinAvgFragmentSize() {
        return minAvgFragmentSize;
    }

    /**
     * Sets the value of the minAvgFragmentSize property.
     * 
     */
    public void setMinAvgFragmentSize(float value) {
        this.minAvgFragmentSize = value;
    }

    /**
     * Gets the value of the maxAvgFragmentSize property.
     * 
     */
    public float getMaxAvgFragmentSize() {
        return maxAvgFragmentSize;
    }

    /**
     * Sets the value of the maxAvgFragmentSize property.
     * 
     */
    public void setMaxAvgFragmentSize(float value) {
        this.maxAvgFragmentSize = value;
    }

    /**
     * Gets the value of the minBCR property.
     * 
     */
    public double getMinBCR() {
        return minBCR;
    }

    /**
     * Sets the value of the minBCR property.
     * 
     */
    public void setMinBCR(double value) {
        this.minBCR = value;
    }

    /**
     * Gets the value of the maxBCR property.
     * 
     */
    public double getMaxBCR() {
        return maxBCR;
    }

    /**
     * Sets the value of the maxBCR property.
     * 
     */
    public void setMaxBCR(double value) {
        this.maxBCR = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            int theNumClusters;
            theNumClusters = this.getNumClusters();
            strategy.appendField(locator, this, "numClusters", buffer, theNumClusters);
        }
        {
            int theMinClusterSize;
            theMinClusterSize = this.getMinClusterSize();
            strategy.appendField(locator, this, "minClusterSize", buffer, theMinClusterSize);
        }
        {
            int theMaxClusterSize;
            theMaxClusterSize = this.getMaxClusterSize();
            strategy.appendField(locator, this, "maxClusterSize", buffer, theMaxClusterSize);
        }
        {
            float theMinAvgFragmentSize;
            theMinAvgFragmentSize = this.getMinAvgFragmentSize();
            strategy.appendField(locator, this, "minAvgFragmentSize", buffer, theMinAvgFragmentSize);
        }
        {
            float theMaxAvgFragmentSize;
            theMaxAvgFragmentSize = this.getMaxAvgFragmentSize();
            strategy.appendField(locator, this, "maxAvgFragmentSize", buffer, theMaxAvgFragmentSize);
        }
        {
            double theMinBCR;
            theMinBCR = this.getMinBCR();
            strategy.appendField(locator, this, "minBCR", buffer, theMinBCR);
        }
        {
            double theMaxBCR;
            theMaxBCR = this.getMaxBCR();
            strategy.appendField(locator, this, "maxBCR", buffer, theMaxBCR);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ClusteringSummaryType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ClusteringSummaryType that = ((ClusteringSummaryType) object);
        {
            int lhsNumClusters;
            lhsNumClusters = this.getNumClusters();
            int rhsNumClusters;
            rhsNumClusters = that.getNumClusters();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numClusters", lhsNumClusters), LocatorUtils.property(thatLocator, "numClusters", rhsNumClusters), lhsNumClusters, rhsNumClusters)) {
                return false;
            }
        }
        {
            int lhsMinClusterSize;
            lhsMinClusterSize = this.getMinClusterSize();
            int rhsMinClusterSize;
            rhsMinClusterSize = that.getMinClusterSize();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "minClusterSize", lhsMinClusterSize), LocatorUtils.property(thatLocator, "minClusterSize", rhsMinClusterSize), lhsMinClusterSize, rhsMinClusterSize)) {
                return false;
            }
        }
        {
            int lhsMaxClusterSize;
            lhsMaxClusterSize = this.getMaxClusterSize();
            int rhsMaxClusterSize;
            rhsMaxClusterSize = that.getMaxClusterSize();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maxClusterSize", lhsMaxClusterSize), LocatorUtils.property(thatLocator, "maxClusterSize", rhsMaxClusterSize), lhsMaxClusterSize, rhsMaxClusterSize)) {
                return false;
            }
        }
        {
            float lhsMinAvgFragmentSize;
            lhsMinAvgFragmentSize = this.getMinAvgFragmentSize();
            float rhsMinAvgFragmentSize;
            rhsMinAvgFragmentSize = that.getMinAvgFragmentSize();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "minAvgFragmentSize", lhsMinAvgFragmentSize), LocatorUtils.property(thatLocator, "minAvgFragmentSize", rhsMinAvgFragmentSize), lhsMinAvgFragmentSize, rhsMinAvgFragmentSize)) {
                return false;
            }
        }
        {
            float lhsMaxAvgFragmentSize;
            lhsMaxAvgFragmentSize = this.getMaxAvgFragmentSize();
            float rhsMaxAvgFragmentSize;
            rhsMaxAvgFragmentSize = that.getMaxAvgFragmentSize();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maxAvgFragmentSize", lhsMaxAvgFragmentSize), LocatorUtils.property(thatLocator, "maxAvgFragmentSize", rhsMaxAvgFragmentSize), lhsMaxAvgFragmentSize, rhsMaxAvgFragmentSize)) {
                return false;
            }
        }
        {
            double lhsMinBCR;
            lhsMinBCR = this.getMinBCR();
            double rhsMinBCR;
            rhsMinBCR = that.getMinBCR();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "minBCR", lhsMinBCR), LocatorUtils.property(thatLocator, "minBCR", rhsMinBCR), lhsMinBCR, rhsMinBCR)) {
                return false;
            }
        }
        {
            double lhsMaxBCR;
            lhsMaxBCR = this.getMaxBCR();
            double rhsMaxBCR;
            rhsMaxBCR = that.getMaxBCR();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maxBCR", lhsMaxBCR), LocatorUtils.property(thatLocator, "maxBCR", rhsMaxBCR), lhsMaxBCR, rhsMaxBCR)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            int theNumClusters;
            theNumClusters = this.getNumClusters();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numClusters", theNumClusters), currentHashCode, theNumClusters);
        }
        {
            int theMinClusterSize;
            theMinClusterSize = this.getMinClusterSize();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "minClusterSize", theMinClusterSize), currentHashCode, theMinClusterSize);
        }
        {
            int theMaxClusterSize;
            theMaxClusterSize = this.getMaxClusterSize();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "maxClusterSize", theMaxClusterSize), currentHashCode, theMaxClusterSize);
        }
        {
            float theMinAvgFragmentSize;
            theMinAvgFragmentSize = this.getMinAvgFragmentSize();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "minAvgFragmentSize", theMinAvgFragmentSize), currentHashCode, theMinAvgFragmentSize);
        }
        {
            float theMaxAvgFragmentSize;
            theMaxAvgFragmentSize = this.getMaxAvgFragmentSize();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "maxAvgFragmentSize", theMaxAvgFragmentSize), currentHashCode, theMaxAvgFragmentSize);
        }
        {
            double theMinBCR;
            theMinBCR = this.getMinBCR();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "minBCR", theMinBCR), currentHashCode, theMinBCR);
        }
        {
            double theMaxBCR;
            theMaxBCR = this.getMaxBCR();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "maxBCR", theMaxBCR), currentHashCode, theMaxBCR);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
