//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 04:10:32 PM EST 
//


package org.apromore.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for FragmentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FragmentData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FragmentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FragmentLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FragmentSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProcessAssociations" type="{urn:qut-edu-au:schema:apromore:manager}ProcessAssociationsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FragmentData", propOrder = {
    "fragmentId",
    "fragmentLabel",
    "distance",
    "fragmentSize",
    "processAssociations"
})
public class FragmentData
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "FragmentId", required = true)
    protected String fragmentId;
    @XmlElement(name = "FragmentLabel", required = true)
    protected String fragmentLabel;
    @XmlElement(name = "Distance")
    protected double distance;
    @XmlElement(name = "FragmentSize")
    protected int fragmentSize;
    @XmlElement(name = "ProcessAssociations")
    protected List<ProcessAssociationsType> processAssociations;

    /**
     * Gets the value of the fragmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentId() {
        return fragmentId;
    }

    /**
     * Sets the value of the fragmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentId(String value) {
        this.fragmentId = value;
    }

    /**
     * Gets the value of the fragmentLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentLabel() {
        return fragmentLabel;
    }

    /**
     * Sets the value of the fragmentLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentLabel(String value) {
        this.fragmentLabel = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public double getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(double value) {
        this.distance = value;
    }

    /**
     * Gets the value of the fragmentSize property.
     * 
     */
    public int getFragmentSize() {
        return fragmentSize;
    }

    /**
     * Sets the value of the fragmentSize property.
     * 
     */
    public void setFragmentSize(int value) {
        this.fragmentSize = value;
    }

    /**
     * Gets the value of the processAssociations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processAssociations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessAssociations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessAssociationsType }
     * 
     * 
     */
    public List<ProcessAssociationsType> getProcessAssociations() {
        if (processAssociations == null) {
            processAssociations = new ArrayList<ProcessAssociationsType>();
        }
        return this.processAssociations;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theFragmentId;
            theFragmentId = this.getFragmentId();
            strategy.appendField(locator, this, "fragmentId", buffer, theFragmentId);
        }
        {
            String theFragmentLabel;
            theFragmentLabel = this.getFragmentLabel();
            strategy.appendField(locator, this, "fragmentLabel", buffer, theFragmentLabel);
        }
        {
            double theDistance;
            theDistance = this.getDistance();
            strategy.appendField(locator, this, "distance", buffer, theDistance);
        }
        {
            int theFragmentSize;
            theFragmentSize = this.getFragmentSize();
            strategy.appendField(locator, this, "fragmentSize", buffer, theFragmentSize);
        }
        {
            List<ProcessAssociationsType> theProcessAssociations;
            theProcessAssociations = this.getProcessAssociations();
            strategy.appendField(locator, this, "processAssociations", buffer, theProcessAssociations);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof FragmentData)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final FragmentData that = ((FragmentData) object);
        {
            String lhsFragmentId;
            lhsFragmentId = this.getFragmentId();
            String rhsFragmentId;
            rhsFragmentId = that.getFragmentId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fragmentId", lhsFragmentId), LocatorUtils.property(thatLocator, "fragmentId", rhsFragmentId), lhsFragmentId, rhsFragmentId)) {
                return false;
            }
        }
        {
            String lhsFragmentLabel;
            lhsFragmentLabel = this.getFragmentLabel();
            String rhsFragmentLabel;
            rhsFragmentLabel = that.getFragmentLabel();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fragmentLabel", lhsFragmentLabel), LocatorUtils.property(thatLocator, "fragmentLabel", rhsFragmentLabel), lhsFragmentLabel, rhsFragmentLabel)) {
                return false;
            }
        }
        {
            double lhsDistance;
            lhsDistance = this.getDistance();
            double rhsDistance;
            rhsDistance = that.getDistance();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "distance", lhsDistance), LocatorUtils.property(thatLocator, "distance", rhsDistance), lhsDistance, rhsDistance)) {
                return false;
            }
        }
        {
            int lhsFragmentSize;
            lhsFragmentSize = this.getFragmentSize();
            int rhsFragmentSize;
            rhsFragmentSize = that.getFragmentSize();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fragmentSize", lhsFragmentSize), LocatorUtils.property(thatLocator, "fragmentSize", rhsFragmentSize), lhsFragmentSize, rhsFragmentSize)) {
                return false;
            }
        }
        {
            List<ProcessAssociationsType> lhsProcessAssociations;
            lhsProcessAssociations = this.getProcessAssociations();
            List<ProcessAssociationsType> rhsProcessAssociations;
            rhsProcessAssociations = that.getProcessAssociations();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processAssociations", lhsProcessAssociations), LocatorUtils.property(thatLocator, "processAssociations", rhsProcessAssociations), lhsProcessAssociations, rhsProcessAssociations)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theFragmentId;
            theFragmentId = this.getFragmentId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fragmentId", theFragmentId), currentHashCode, theFragmentId);
        }
        {
            String theFragmentLabel;
            theFragmentLabel = this.getFragmentLabel();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fragmentLabel", theFragmentLabel), currentHashCode, theFragmentLabel);
        }
        {
            double theDistance;
            theDistance = this.getDistance();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "distance", theDistance), currentHashCode, theDistance);
        }
        {
            int theFragmentSize;
            theFragmentSize = this.getFragmentSize();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fragmentSize", theFragmentSize), currentHashCode, theFragmentSize);
        }
        {
            List<ProcessAssociationsType> theProcessAssociations;
            theProcessAssociations = this.getProcessAssociations();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "processAssociations", theProcessAssociations), currentHashCode, theProcessAssociations);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
