//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 04:10:32 PM EST 
//


package org.apromore.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apromore.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReadProcessSummariesRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadProcessSummariesRequest");
    private final static QName _ImportProcessResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ImportProcessResponse");
    private final static QName _WriteAnnotationRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "WriteAnnotationRequest");
    private final static QName _DeleteProcessVersionsRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "DeleteProcessVersionsRequest");
    private final static QName _DeleteEditSessionRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "DeleteEditSessionRequest");
    private final static QName _GetClusteringSummaryRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClusteringSummaryRequest");
    private final static QName _PairwiseDistancesResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "PairwiseDistancesResponse");
    private final static QName _WriteEditSessionResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "WriteEditSessionResponse");
    private final static QName _CreateClustersResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "CreateClustersResponse");
    private final static QName _FragmentResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "FragmentResponse");
    private final static QName _ReadDomainsRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadDomainsRequest");
    private final static QName _DeleteProcessVersionsResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "DeleteProcessVersionsResponse");
    private final static QName _WriteUserRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "WriteUserRequest");
    private final static QName _ReadEditSessionRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadEditSessionRequest");
    private final static QName _ReadAllUsersResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadAllUsersResponse");
    private final static QName _ReadAllUsersRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadAllUsersRequest");
    private final static QName _ReadProcessSummariesResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadProcessSummariesResponse");
    private final static QName _GetClustersRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClustersRequest");
    private final static QName _MergeProcessesResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "MergeProcessesResponse");
    private final static QName _SearchForSimilarProcessesResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "SearchForSimilarProcessesResponse");
    private final static QName _ImportProcessRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ImportProcessRequest");
    private final static QName _EditProcessDataResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "EditProcessDataResponse");
    private final static QName _ExportFormatResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ExportFormatResponse");
    private final static QName _ReadUserResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadUserResponse");
    private final static QName _ReadEditSessionResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadEditSessionResponse");
    private final static QName _GetClusterRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClusterRequest");
    private final static QName _MergeProcessesRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "MergeProcessesRequest");
    private final static QName _GetProcessDataRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetProcessDataRequest");
    private final static QName _ExportFormatRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ExportFormatRequest");
    private final static QName _SearchForSimilarProcessesRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "SearchForSimilarProcessesRequest");
    private final static QName _GetClusterResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClusterResponse");
    private final static QName _GetClusterSummariesResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClusterSummariesResponse");
    private final static QName _WriteEditSessionRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "WriteEditSessionRequest");
    private final static QName _GetClustersResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClustersResponse");
    private final static QName _GetFragmentRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetFragmentRequest");
    private final static QName _ReadNativeTypesResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadNativeTypesResponse");
    private final static QName _ReadDomainsResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadDomainsResponse");
    private final static QName _GetClusteringSummaryResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClusteringSummaryResponse");
    private final static QName _WriteUserResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "WriteUserResponse");
    private final static QName _GetProcessDataResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetProcessDataResponse");
    private final static QName _UpdateProcessResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "UpdateProcessResponse");
    private final static QName _ReadNativeTypesRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadNativeTypesRequest");
    private final static QName _WriteAnnotationResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "WriteAnnotationResponse");
    private final static QName _UpdateProcessRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "UpdateProcessRequest");
    private final static QName _CreateClustersRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "CreateClustersRequest");
    private final static QName _ReadUserRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "ReadUserRequest");
    private final static QName _GetClusterSummariesRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "GetClusterSummariesRequest");
    private final static QName _DeleteEditSessionResponse_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "DeleteEditSessionResponse");
    private final static QName _EditProcessDataRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "EditProcessDataRequest");
    private final static QName _PairwiseDistancesRequest_QNAME = new QName("urn:qut-edu-au:schema:apromore:manager", "PairwiseDistancesRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apromore.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteEditSessionInputMsgType }
     * 
     */
    public DeleteEditSessionInputMsgType createDeleteEditSessionInputMsgType() {
        return new DeleteEditSessionInputMsgType();
    }

    /**
     * Create an instance of {@link GetClusteringSummaryInputMsgType }
     * 
     */
    public GetClusteringSummaryInputMsgType createGetClusteringSummaryInputMsgType() {
        return new GetClusteringSummaryInputMsgType();
    }

    /**
     * Create an instance of {@link GetPairwiseDistancesOutputMsgType }
     * 
     */
    public GetPairwiseDistancesOutputMsgType createGetPairwiseDistancesOutputMsgType() {
        return new GetPairwiseDistancesOutputMsgType();
    }

    /**
     * Create an instance of {@link WriteEditSessionOutputMsgType }
     * 
     */
    public WriteEditSessionOutputMsgType createWriteEditSessionOutputMsgType() {
        return new WriteEditSessionOutputMsgType();
    }

    /**
     * Create an instance of {@link CreateClustersOutputMsgType }
     * 
     */
    public CreateClustersOutputMsgType createCreateClustersOutputMsgType() {
        return new CreateClustersOutputMsgType();
    }

    /**
     * Create an instance of {@link ReadProcessSummariesInputMsgType }
     * 
     */
    public ReadProcessSummariesInputMsgType createReadProcessSummariesInputMsgType() {
        return new ReadProcessSummariesInputMsgType();
    }

    /**
     * Create an instance of {@link ImportProcessOutputMsgType }
     * 
     */
    public ImportProcessOutputMsgType createImportProcessOutputMsgType() {
        return new ImportProcessOutputMsgType();
    }

    /**
     * Create an instance of {@link WriteAnnotationInputMsgType }
     * 
     */
    public WriteAnnotationInputMsgType createWriteAnnotationInputMsgType() {
        return new WriteAnnotationInputMsgType();
    }

    /**
     * Create an instance of {@link DeleteProcessVersionsInputMsgType }
     * 
     */
    public DeleteProcessVersionsInputMsgType createDeleteProcessVersionsInputMsgType() {
        return new DeleteProcessVersionsInputMsgType();
    }

    /**
     * Create an instance of {@link ReadEditSessionInputMsgType }
     * 
     */
    public ReadEditSessionInputMsgType createReadEditSessionInputMsgType() {
        return new ReadEditSessionInputMsgType();
    }

    /**
     * Create an instance of {@link ReadAllUsersOutputMsgType }
     * 
     */
    public ReadAllUsersOutputMsgType createReadAllUsersOutputMsgType() {
        return new ReadAllUsersOutputMsgType();
    }

    /**
     * Create an instance of {@link ReadAllUsersInputMsgType }
     * 
     */
    public ReadAllUsersInputMsgType createReadAllUsersInputMsgType() {
        return new ReadAllUsersInputMsgType();
    }

    /**
     * Create an instance of {@link ReadProcessSummariesOutputMsgType }
     * 
     */
    public ReadProcessSummariesOutputMsgType createReadProcessSummariesOutputMsgType() {
        return new ReadProcessSummariesOutputMsgType();
    }

    /**
     * Create an instance of {@link FragmentResponseType }
     * 
     */
    public FragmentResponseType createFragmentResponseType() {
        return new FragmentResponseType();
    }

    /**
     * Create an instance of {@link ReadDomainsInputMsgType }
     * 
     */
    public ReadDomainsInputMsgType createReadDomainsInputMsgType() {
        return new ReadDomainsInputMsgType();
    }

    /**
     * Create an instance of {@link DeleteProcessVersionsOutputMsgType }
     * 
     */
    public DeleteProcessVersionsOutputMsgType createDeleteProcessVersionsOutputMsgType() {
        return new DeleteProcessVersionsOutputMsgType();
    }

    /**
     * Create an instance of {@link WriteUserInputMsgType }
     * 
     */
    public WriteUserInputMsgType createWriteUserInputMsgType() {
        return new WriteUserInputMsgType();
    }

    /**
     * Create an instance of {@link GetProcessDataInputMsgType }
     * 
     */
    public GetProcessDataInputMsgType createGetProcessDataInputMsgType() {
        return new GetProcessDataInputMsgType();
    }

    /**
     * Create an instance of {@link SearchForSimilarProcessesInputMsgType }
     * 
     */
    public SearchForSimilarProcessesInputMsgType createSearchForSimilarProcessesInputMsgType() {
        return new SearchForSimilarProcessesInputMsgType();
    }

    /**
     * Create an instance of {@link ExportFormatInputMsgType }
     * 
     */
    public ExportFormatInputMsgType createExportFormatInputMsgType() {
        return new ExportFormatInputMsgType();
    }

    /**
     * Create an instance of {@link GetClustersResponseType }
     * 
     */
    public GetClustersResponseType createGetClustersResponseType() {
        return new GetClustersResponseType();
    }

    /**
     * Create an instance of {@link WriteEditSessionInputMsgType }
     * 
     */
    public WriteEditSessionInputMsgType createWriteEditSessionInputMsgType() {
        return new WriteEditSessionInputMsgType();
    }

    /**
     * Create an instance of {@link GetClusterSummariesOutputMsgType }
     * 
     */
    public GetClusterSummariesOutputMsgType createGetClusterSummariesOutputMsgType() {
        return new GetClusterSummariesOutputMsgType();
    }

    /**
     * Create an instance of {@link GetClusterOutputMsgType }
     * 
     */
    public GetClusterOutputMsgType createGetClusterOutputMsgType() {
        return new GetClusterOutputMsgType();
    }

    /**
     * Create an instance of {@link GetFragmentRequestType }
     * 
     */
    public GetFragmentRequestType createGetFragmentRequestType() {
        return new GetFragmentRequestType();
    }

    /**
     * Create an instance of {@link ReadNativeTypesOutputMsgType }
     * 
     */
    public ReadNativeTypesOutputMsgType createReadNativeTypesOutputMsgType() {
        return new ReadNativeTypesOutputMsgType();
    }

    /**
     * Create an instance of {@link GetClustersRequestType }
     * 
     */
    public GetClustersRequestType createGetClustersRequestType() {
        return new GetClustersRequestType();
    }

    /**
     * Create an instance of {@link MergeProcessesOutputMsgType }
     * 
     */
    public MergeProcessesOutputMsgType createMergeProcessesOutputMsgType() {
        return new MergeProcessesOutputMsgType();
    }

    /**
     * Create an instance of {@link ImportProcessInputMsgType }
     * 
     */
    public ImportProcessInputMsgType createImportProcessInputMsgType() {
        return new ImportProcessInputMsgType();
    }

    /**
     * Create an instance of {@link SearchForSimilarProcessesOutputMsgType }
     * 
     */
    public SearchForSimilarProcessesOutputMsgType createSearchForSimilarProcessesOutputMsgType() {
        return new SearchForSimilarProcessesOutputMsgType();
    }

    /**
     * Create an instance of {@link EditProcessDataOutputMsgType }
     * 
     */
    public EditProcessDataOutputMsgType createEditProcessDataOutputMsgType() {
        return new EditProcessDataOutputMsgType();
    }

    /**
     * Create an instance of {@link ReadEditSessionOutputMsgType }
     * 
     */
    public ReadEditSessionOutputMsgType createReadEditSessionOutputMsgType() {
        return new ReadEditSessionOutputMsgType();
    }

    /**
     * Create an instance of {@link GetClusterInputMsgType }
     * 
     */
    public GetClusterInputMsgType createGetClusterInputMsgType() {
        return new GetClusterInputMsgType();
    }

    /**
     * Create an instance of {@link ExportFormatOutputMsgType }
     * 
     */
    public ExportFormatOutputMsgType createExportFormatOutputMsgType() {
        return new ExportFormatOutputMsgType();
    }

    /**
     * Create an instance of {@link ReadUserOutputMsgType }
     * 
     */
    public ReadUserOutputMsgType createReadUserOutputMsgType() {
        return new ReadUserOutputMsgType();
    }

    /**
     * Create an instance of {@link MergeProcessesInputMsgType }
     * 
     */
    public MergeProcessesInputMsgType createMergeProcessesInputMsgType() {
        return new MergeProcessesInputMsgType();
    }

    /**
     * Create an instance of {@link ReadUserInputMsgType }
     * 
     */
    public ReadUserInputMsgType createReadUserInputMsgType() {
        return new ReadUserInputMsgType();
    }

    /**
     * Create an instance of {@link CreateClustersInputMsgType }
     * 
     */
    public CreateClustersInputMsgType createCreateClustersInputMsgType() {
        return new CreateClustersInputMsgType();
    }

    /**
     * Create an instance of {@link GetClusterSummariesInputMsgType }
     * 
     */
    public GetClusterSummariesInputMsgType createGetClusterSummariesInputMsgType() {
        return new GetClusterSummariesInputMsgType();
    }

    /**
     * Create an instance of {@link DeleteEditSessionOutputMsgType }
     * 
     */
    public DeleteEditSessionOutputMsgType createDeleteEditSessionOutputMsgType() {
        return new DeleteEditSessionOutputMsgType();
    }

    /**
     * Create an instance of {@link EditProcessDataInputMsgType }
     * 
     */
    public EditProcessDataInputMsgType createEditProcessDataInputMsgType() {
        return new EditProcessDataInputMsgType();
    }

    /**
     * Create an instance of {@link GetPairwiseDistancesInputMsgType }
     * 
     */
    public GetPairwiseDistancesInputMsgType createGetPairwiseDistancesInputMsgType() {
        return new GetPairwiseDistancesInputMsgType();
    }

    /**
     * Create an instance of {@link ReadDomainsOutputMsgType }
     * 
     */
    public ReadDomainsOutputMsgType createReadDomainsOutputMsgType() {
        return new ReadDomainsOutputMsgType();
    }

    /**
     * Create an instance of {@link GetClusteringSummaryOutputMsgType }
     * 
     */
    public GetClusteringSummaryOutputMsgType createGetClusteringSummaryOutputMsgType() {
        return new GetClusteringSummaryOutputMsgType();
    }

    /**
     * Create an instance of {@link GetProcessDataOutputMsgType }
     * 
     */
    public GetProcessDataOutputMsgType createGetProcessDataOutputMsgType() {
        return new GetProcessDataOutputMsgType();
    }

    /**
     * Create an instance of {@link UpdateProcessOutputMsgType }
     * 
     */
    public UpdateProcessOutputMsgType createUpdateProcessOutputMsgType() {
        return new UpdateProcessOutputMsgType();
    }

    /**
     * Create an instance of {@link WriteUserOutputMsgType }
     * 
     */
    public WriteUserOutputMsgType createWriteUserOutputMsgType() {
        return new WriteUserOutputMsgType();
    }

    /**
     * Create an instance of {@link WriteAnnotationOutputMsgType }
     * 
     */
    public WriteAnnotationOutputMsgType createWriteAnnotationOutputMsgType() {
        return new WriteAnnotationOutputMsgType();
    }

    /**
     * Create an instance of {@link ReadNativeTypesInputMsgType }
     * 
     */
    public ReadNativeTypesInputMsgType createReadNativeTypesInputMsgType() {
        return new ReadNativeTypesInputMsgType();
    }

    /**
     * Create an instance of {@link UpdateProcessInputMsgType }
     * 
     */
    public UpdateProcessInputMsgType createUpdateProcessInputMsgType() {
        return new UpdateProcessInputMsgType();
    }

    /**
     * Create an instance of {@link StoreCpfInputMsgType }
     * 
     */
    public StoreCpfInputMsgType createStoreCpfInputMsgType() {
        return new StoreCpfInputMsgType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link FragmentIdsType }
     * 
     */
    public FragmentIdsType createFragmentIdsType() {
        return new FragmentIdsType();
    }

    /**
     * Create an instance of {@link ProcessVersionIdentifierType }
     * 
     */
    public ProcessVersionIdentifierType createProcessVersionIdentifierType() {
        return new ProcessVersionIdentifierType();
    }

    /**
     * Create an instance of {@link ProcessVersionsType }
     * 
     */
    public ProcessVersionsType createProcessVersionsType() {
        return new ProcessVersionsType();
    }

    /**
     * Create an instance of {@link UsernamesType }
     * 
     */
    public UsernamesType createUsernamesType() {
        return new UsernamesType();
    }

    /**
     * Create an instance of {@link ProcessVersionIdsType }
     * 
     */
    public ProcessVersionIdsType createProcessVersionIdsType() {
        return new ProcessVersionIdsType();
    }

    /**
     * Create an instance of {@link DistanceType }
     * 
     */
    public DistanceType createDistanceType() {
        return new DistanceType();
    }

    /**
     * Create an instance of {@link ProcessVersionType }
     * 
     */
    public ProcessVersionType createProcessVersionType() {
        return new ProcessVersionType();
    }

    /**
     * Create an instance of {@link CanoniseVersionOutputMsgType }
     * 
     */
    public CanoniseVersionOutputMsgType createCanoniseVersionOutputMsgType() {
        return new CanoniseVersionOutputMsgType();
    }

    /**
     * Create an instance of {@link GetCpfUriInputMsgType }
     * 
     */
    public GetCpfUriInputMsgType createGetCpfUriInputMsgType() {
        return new GetCpfUriInputMsgType();
    }

    /**
     * Create an instance of {@link AnnotationsType }
     * 
     */
    public AnnotationsType createAnnotationsType() {
        return new AnnotationsType();
    }

    /**
     * Create an instance of {@link ClusterSettingsType }
     * 
     */
    public ClusterSettingsType createClusterSettingsType() {
        return new ClusterSettingsType();
    }

    /**
     * Create an instance of {@link ClusterSummaryType }
     * 
     */
    public ClusterSummaryType createClusterSummaryType() {
        return new ClusterSummaryType();
    }

    /**
     * Create an instance of {@link PairDistancesType }
     * 
     */
    public PairDistancesType createPairDistancesType() {
        return new PairDistancesType();
    }

    /**
     * Create an instance of {@link FragmentType }
     * 
     */
    public FragmentType createFragmentType() {
        return new FragmentType();
    }

    /**
     * Create an instance of {@link EditSessionType }
     * 
     */
    public EditSessionType createEditSessionType() {
        return new EditSessionType();
    }

    /**
     * Create an instance of {@link CanonicalType }
     * 
     */
    public CanonicalType createCanonicalType() {
        return new CanonicalType();
    }

    /**
     * Create an instance of {@link ReadCanonicalsInputMsgType }
     * 
     */
    public ReadCanonicalsInputMsgType createReadCanonicalsInputMsgType() {
        return new ReadCanonicalsInputMsgType();
    }

    /**
     * Create an instance of {@link CanoniseProcessOutputMsgType }
     * 
     */
    public CanoniseProcessOutputMsgType createCanoniseProcessOutputMsgType() {
        return new CanoniseProcessOutputMsgType();
    }

    /**
     * Create an instance of {@link GenerateAnnotationInputMsgType }
     * 
     */
    public GenerateAnnotationInputMsgType createGenerateAnnotationInputMsgType() {
        return new GenerateAnnotationInputMsgType();
    }

    /**
     * Create an instance of {@link FragmentDistancesType }
     * 
     */
    public FragmentDistancesType createFragmentDistancesType() {
        return new FragmentDistancesType();
    }

    /**
     * Create an instance of {@link GetCpfUriOutputMsgType }
     * 
     */
    public GetCpfUriOutputMsgType createGetCpfUriOutputMsgType() {
        return new GetCpfUriOutputMsgType();
    }

    /**
     * Create an instance of {@link NewComplexType }
     * 
     */
    public NewComplexType createNewComplexType() {
        return new NewComplexType();
    }

    /**
     * Create an instance of {@link MergedSource }
     * 
     */
    public MergedSource createMergedSource() {
        return new MergedSource();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link ReadFormatInputMsgType }
     * 
     */
    public ReadFormatInputMsgType createReadFormatInputMsgType() {
        return new ReadFormatInputMsgType();
    }

    /**
     * Create an instance of {@link SearchHistoriesType }
     * 
     */
    public SearchHistoriesType createSearchHistoriesType() {
        return new SearchHistoriesType();
    }

    /**
     * Create an instance of {@link CanoniseVersionInputMsgType }
     * 
     */
    public CanoniseVersionInputMsgType createCanoniseVersionInputMsgType() {
        return new CanoniseVersionInputMsgType();
    }

    /**
     * Create an instance of {@link ClusteringParameterType }
     * 
     */
    public ClusteringParameterType createClusteringParameterType() {
        return new ClusteringParameterType();
    }

    /**
     * Create an instance of {@link VersionSummaryType }
     * 
     */
    public VersionSummaryType createVersionSummaryType() {
        return new VersionSummaryType();
    }

    /**
     * Create an instance of {@link PiarDistanceType }
     * 
     */
    public PiarDistanceType createPiarDistanceType() {
        return new PiarDistanceType();
    }

    /**
     * Create an instance of {@link DeCanoniseProcessInputMsgType }
     * 
     */
    public DeCanoniseProcessInputMsgType createDeCanoniseProcessInputMsgType() {
        return new DeCanoniseProcessInputMsgType();
    }

    /**
     * Create an instance of {@link CanonicalsType }
     * 
     */
    public CanonicalsType createCanonicalsType() {
        return new CanonicalsType();
    }

    /**
     * Create an instance of {@link ReadProcessSummaryInputMsgType }
     * 
     */
    public ReadProcessSummaryInputMsgType createReadProcessSummaryInputMsgType() {
        return new ReadProcessSummaryInputMsgType();
    }

    /**
     * Create an instance of {@link ReadCanonicalsOutputMsgType }
     * 
     */
    public ReadCanonicalsOutputMsgType createReadCanonicalsOutputMsgType() {
        return new ReadCanonicalsOutputMsgType();
    }

    /**
     * Create an instance of {@link CanoniseProcessInputMsgType }
     * 
     */
    public CanoniseProcessInputMsgType createCanoniseProcessInputMsgType() {
        return new CanoniseProcessInputMsgType();
    }

    /**
     * Create an instance of {@link GenerateAnnotationOutputMsgType }
     * 
     */
    public GenerateAnnotationOutputMsgType createGenerateAnnotationOutputMsgType() {
        return new GenerateAnnotationOutputMsgType();
    }

    /**
     * Create an instance of {@link ProcessSummaryType }
     * 
     */
    public ProcessSummaryType createProcessSummaryType() {
        return new ProcessSummaryType();
    }

    /**
     * Create an instance of {@link ConstrainedProcessIdsType }
     * 
     */
    public ConstrainedProcessIdsType createConstrainedProcessIdsType() {
        return new ConstrainedProcessIdsType();
    }

    /**
     * Create an instance of {@link ReadCanonicalAnfOutputMsgType }
     * 
     */
    public ReadCanonicalAnfOutputMsgType createReadCanonicalAnfOutputMsgType() {
        return new ReadCanonicalAnfOutputMsgType();
    }

    /**
     * Create an instance of {@link ReadCanonicalAnfInputMsgType }
     * 
     */
    public ReadCanonicalAnfInputMsgType createReadCanonicalAnfInputMsgType() {
        return new ReadCanonicalAnfInputMsgType();
    }

    /**
     * Create an instance of {@link DomainsType }
     * 
     */
    public DomainsType createDomainsType() {
        return new DomainsType();
    }

    /**
     * Create an instance of {@link DeCanoniseProcessOutputMsgType }
     * 
     */
    public DeCanoniseProcessOutputMsgType createDeCanoniseProcessOutputMsgType() {
        return new DeCanoniseProcessOutputMsgType();
    }

    /**
     * Create an instance of {@link StoreVersionInputMsgType }
     * 
     */
    public StoreVersionInputMsgType createStoreVersionInputMsgType() {
        return new StoreVersionInputMsgType();
    }

    /**
     * Create an instance of {@link ProcessVersionIdType }
     * 
     */
    public ProcessVersionIdType createProcessVersionIdType() {
        return new ProcessVersionIdType();
    }

    /**
     * Create an instance of {@link StoreCpfOutputMsgType }
     * 
     */
    public StoreCpfOutputMsgType createStoreCpfOutputMsgType() {
        return new StoreCpfOutputMsgType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ClusteringSummaryType }
     * 
     */
    public ClusteringSummaryType createClusteringSummaryType() {
        return new ClusteringSummaryType();
    }

    /**
     * Create an instance of {@link NativeTypesType }
     * 
     */
    public NativeTypesType createNativeTypesType() {
        return new NativeTypesType();
    }

    /**
     * Create an instance of {@link StoreNativeCpfInputMsgType }
     * 
     */
    public StoreNativeCpfInputMsgType createStoreNativeCpfInputMsgType() {
        return new StoreNativeCpfInputMsgType();
    }

    /**
     * Create an instance of {@link FragmentData }
     * 
     */
    public FragmentData createFragmentData() {
        return new FragmentData();
    }

    /**
     * Create an instance of {@link StoreVersionOutputMsgType }
     * 
     */
    public StoreVersionOutputMsgType createStoreVersionOutputMsgType() {
        return new StoreVersionOutputMsgType();
    }

    /**
     * Create an instance of {@link MergedSources }
     * 
     */
    public MergedSources createMergedSources() {
        return new MergedSources();
    }

    /**
     * Create an instance of {@link ReadFormatOutputMsgType }
     * 
     */
    public ReadFormatOutputMsgType createReadFormatOutputMsgType() {
        return new ReadFormatOutputMsgType();
    }

    /**
     * Create an instance of {@link StoreNativeOutputMsgType }
     * 
     */
    public StoreNativeOutputMsgType createStoreNativeOutputMsgType() {
        return new StoreNativeOutputMsgType();
    }

    /**
     * Create an instance of {@link ProcessSummariesType }
     * 
     */
    public ProcessSummariesType createProcessSummariesType() {
        return new ProcessSummariesType();
    }

    /**
     * Create an instance of {@link StoreNativeCpfOutputMsgType }
     * 
     */
    public StoreNativeCpfOutputMsgType createStoreNativeCpfOutputMsgType() {
        return new StoreNativeCpfOutputMsgType();
    }

    /**
     * Create an instance of {@link ProcessAssociationsType }
     * 
     */
    public ProcessAssociationsType createProcessAssociationsType() {
        return new ProcessAssociationsType();
    }

    /**
     * Create an instance of {@link ClusterFilterType }
     * 
     */
    public ClusterFilterType createClusterFilterType() {
        return new ClusterFilterType();
    }

    /**
     * Create an instance of {@link StoreNativeInputMsgType }
     * 
     */
    public StoreNativeInputMsgType createStoreNativeInputMsgType() {
        return new StoreNativeInputMsgType();
    }

    /**
     * Create an instance of {@link ClusterType }
     * 
     */
    public ClusterType createClusterType() {
        return new ClusterType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadProcessSummariesInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadProcessSummariesRequest")
    public JAXBElement<ReadProcessSummariesInputMsgType> createReadProcessSummariesRequest(ReadProcessSummariesInputMsgType value) {
        return new JAXBElement<ReadProcessSummariesInputMsgType>(_ReadProcessSummariesRequest_QNAME, ReadProcessSummariesInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportProcessOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ImportProcessResponse")
    public JAXBElement<ImportProcessOutputMsgType> createImportProcessResponse(ImportProcessOutputMsgType value) {
        return new JAXBElement<ImportProcessOutputMsgType>(_ImportProcessResponse_QNAME, ImportProcessOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WriteAnnotationInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "WriteAnnotationRequest")
    public JAXBElement<WriteAnnotationInputMsgType> createWriteAnnotationRequest(WriteAnnotationInputMsgType value) {
        return new JAXBElement<WriteAnnotationInputMsgType>(_WriteAnnotationRequest_QNAME, WriteAnnotationInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteProcessVersionsInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "DeleteProcessVersionsRequest")
    public JAXBElement<DeleteProcessVersionsInputMsgType> createDeleteProcessVersionsRequest(DeleteProcessVersionsInputMsgType value) {
        return new JAXBElement<DeleteProcessVersionsInputMsgType>(_DeleteProcessVersionsRequest_QNAME, DeleteProcessVersionsInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteEditSessionInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "DeleteEditSessionRequest")
    public JAXBElement<DeleteEditSessionInputMsgType> createDeleteEditSessionRequest(DeleteEditSessionInputMsgType value) {
        return new JAXBElement<DeleteEditSessionInputMsgType>(_DeleteEditSessionRequest_QNAME, DeleteEditSessionInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusteringSummaryInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClusteringSummaryRequest")
    public JAXBElement<GetClusteringSummaryInputMsgType> createGetClusteringSummaryRequest(GetClusteringSummaryInputMsgType value) {
        return new JAXBElement<GetClusteringSummaryInputMsgType>(_GetClusteringSummaryRequest_QNAME, GetClusteringSummaryInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPairwiseDistancesOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "PairwiseDistancesResponse")
    public JAXBElement<GetPairwiseDistancesOutputMsgType> createPairwiseDistancesResponse(GetPairwiseDistancesOutputMsgType value) {
        return new JAXBElement<GetPairwiseDistancesOutputMsgType>(_PairwiseDistancesResponse_QNAME, GetPairwiseDistancesOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WriteEditSessionOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "WriteEditSessionResponse")
    public JAXBElement<WriteEditSessionOutputMsgType> createWriteEditSessionResponse(WriteEditSessionOutputMsgType value) {
        return new JAXBElement<WriteEditSessionOutputMsgType>(_WriteEditSessionResponse_QNAME, WriteEditSessionOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateClustersOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "CreateClustersResponse")
    public JAXBElement<CreateClustersOutputMsgType> createCreateClustersResponse(CreateClustersOutputMsgType value) {
        return new JAXBElement<CreateClustersOutputMsgType>(_CreateClustersResponse_QNAME, CreateClustersOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FragmentResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "FragmentResponse")
    public JAXBElement<FragmentResponseType> createFragmentResponse(FragmentResponseType value) {
        return new JAXBElement<FragmentResponseType>(_FragmentResponse_QNAME, FragmentResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadDomainsInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadDomainsRequest")
    public JAXBElement<ReadDomainsInputMsgType> createReadDomainsRequest(ReadDomainsInputMsgType value) {
        return new JAXBElement<ReadDomainsInputMsgType>(_ReadDomainsRequest_QNAME, ReadDomainsInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteProcessVersionsOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "DeleteProcessVersionsResponse")
    public JAXBElement<DeleteProcessVersionsOutputMsgType> createDeleteProcessVersionsResponse(DeleteProcessVersionsOutputMsgType value) {
        return new JAXBElement<DeleteProcessVersionsOutputMsgType>(_DeleteProcessVersionsResponse_QNAME, DeleteProcessVersionsOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WriteUserInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "WriteUserRequest")
    public JAXBElement<WriteUserInputMsgType> createWriteUserRequest(WriteUserInputMsgType value) {
        return new JAXBElement<WriteUserInputMsgType>(_WriteUserRequest_QNAME, WriteUserInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadEditSessionInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadEditSessionRequest")
    public JAXBElement<ReadEditSessionInputMsgType> createReadEditSessionRequest(ReadEditSessionInputMsgType value) {
        return new JAXBElement<ReadEditSessionInputMsgType>(_ReadEditSessionRequest_QNAME, ReadEditSessionInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAllUsersOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadAllUsersResponse")
    public JAXBElement<ReadAllUsersOutputMsgType> createReadAllUsersResponse(ReadAllUsersOutputMsgType value) {
        return new JAXBElement<ReadAllUsersOutputMsgType>(_ReadAllUsersResponse_QNAME, ReadAllUsersOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAllUsersInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadAllUsersRequest")
    public JAXBElement<ReadAllUsersInputMsgType> createReadAllUsersRequest(ReadAllUsersInputMsgType value) {
        return new JAXBElement<ReadAllUsersInputMsgType>(_ReadAllUsersRequest_QNAME, ReadAllUsersInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadProcessSummariesOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadProcessSummariesResponse")
    public JAXBElement<ReadProcessSummariesOutputMsgType> createReadProcessSummariesResponse(ReadProcessSummariesOutputMsgType value) {
        return new JAXBElement<ReadProcessSummariesOutputMsgType>(_ReadProcessSummariesResponse_QNAME, ReadProcessSummariesOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClustersRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClustersRequest")
    public JAXBElement<GetClustersRequestType> createGetClustersRequest(GetClustersRequestType value) {
        return new JAXBElement<GetClustersRequestType>(_GetClustersRequest_QNAME, GetClustersRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MergeProcessesOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "MergeProcessesResponse")
    public JAXBElement<MergeProcessesOutputMsgType> createMergeProcessesResponse(MergeProcessesOutputMsgType value) {
        return new JAXBElement<MergeProcessesOutputMsgType>(_MergeProcessesResponse_QNAME, MergeProcessesOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchForSimilarProcessesOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "SearchForSimilarProcessesResponse")
    public JAXBElement<SearchForSimilarProcessesOutputMsgType> createSearchForSimilarProcessesResponse(SearchForSimilarProcessesOutputMsgType value) {
        return new JAXBElement<SearchForSimilarProcessesOutputMsgType>(_SearchForSimilarProcessesResponse_QNAME, SearchForSimilarProcessesOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportProcessInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ImportProcessRequest")
    public JAXBElement<ImportProcessInputMsgType> createImportProcessRequest(ImportProcessInputMsgType value) {
        return new JAXBElement<ImportProcessInputMsgType>(_ImportProcessRequest_QNAME, ImportProcessInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditProcessDataOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "EditProcessDataResponse")
    public JAXBElement<EditProcessDataOutputMsgType> createEditProcessDataResponse(EditProcessDataOutputMsgType value) {
        return new JAXBElement<EditProcessDataOutputMsgType>(_EditProcessDataResponse_QNAME, EditProcessDataOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExportFormatOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ExportFormatResponse")
    public JAXBElement<ExportFormatOutputMsgType> createExportFormatResponse(ExportFormatOutputMsgType value) {
        return new JAXBElement<ExportFormatOutputMsgType>(_ExportFormatResponse_QNAME, ExportFormatOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadUserOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadUserResponse")
    public JAXBElement<ReadUserOutputMsgType> createReadUserResponse(ReadUserOutputMsgType value) {
        return new JAXBElement<ReadUserOutputMsgType>(_ReadUserResponse_QNAME, ReadUserOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadEditSessionOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadEditSessionResponse")
    public JAXBElement<ReadEditSessionOutputMsgType> createReadEditSessionResponse(ReadEditSessionOutputMsgType value) {
        return new JAXBElement<ReadEditSessionOutputMsgType>(_ReadEditSessionResponse_QNAME, ReadEditSessionOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusterInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClusterRequest")
    public JAXBElement<GetClusterInputMsgType> createGetClusterRequest(GetClusterInputMsgType value) {
        return new JAXBElement<GetClusterInputMsgType>(_GetClusterRequest_QNAME, GetClusterInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MergeProcessesInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "MergeProcessesRequest")
    public JAXBElement<MergeProcessesInputMsgType> createMergeProcessesRequest(MergeProcessesInputMsgType value) {
        return new JAXBElement<MergeProcessesInputMsgType>(_MergeProcessesRequest_QNAME, MergeProcessesInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessDataInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetProcessDataRequest")
    public JAXBElement<GetProcessDataInputMsgType> createGetProcessDataRequest(GetProcessDataInputMsgType value) {
        return new JAXBElement<GetProcessDataInputMsgType>(_GetProcessDataRequest_QNAME, GetProcessDataInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExportFormatInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ExportFormatRequest")
    public JAXBElement<ExportFormatInputMsgType> createExportFormatRequest(ExportFormatInputMsgType value) {
        return new JAXBElement<ExportFormatInputMsgType>(_ExportFormatRequest_QNAME, ExportFormatInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchForSimilarProcessesInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "SearchForSimilarProcessesRequest")
    public JAXBElement<SearchForSimilarProcessesInputMsgType> createSearchForSimilarProcessesRequest(SearchForSimilarProcessesInputMsgType value) {
        return new JAXBElement<SearchForSimilarProcessesInputMsgType>(_SearchForSimilarProcessesRequest_QNAME, SearchForSimilarProcessesInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusterOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClusterResponse")
    public JAXBElement<GetClusterOutputMsgType> createGetClusterResponse(GetClusterOutputMsgType value) {
        return new JAXBElement<GetClusterOutputMsgType>(_GetClusterResponse_QNAME, GetClusterOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusterSummariesOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClusterSummariesResponse")
    public JAXBElement<GetClusterSummariesOutputMsgType> createGetClusterSummariesResponse(GetClusterSummariesOutputMsgType value) {
        return new JAXBElement<GetClusterSummariesOutputMsgType>(_GetClusterSummariesResponse_QNAME, GetClusterSummariesOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WriteEditSessionInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "WriteEditSessionRequest")
    public JAXBElement<WriteEditSessionInputMsgType> createWriteEditSessionRequest(WriteEditSessionInputMsgType value) {
        return new JAXBElement<WriteEditSessionInputMsgType>(_WriteEditSessionRequest_QNAME, WriteEditSessionInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClustersResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClustersResponse")
    public JAXBElement<GetClustersResponseType> createGetClustersResponse(GetClustersResponseType value) {
        return new JAXBElement<GetClustersResponseType>(_GetClustersResponse_QNAME, GetClustersResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFragmentRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetFragmentRequest")
    public JAXBElement<GetFragmentRequestType> createGetFragmentRequest(GetFragmentRequestType value) {
        return new JAXBElement<GetFragmentRequestType>(_GetFragmentRequest_QNAME, GetFragmentRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadNativeTypesOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadNativeTypesResponse")
    public JAXBElement<ReadNativeTypesOutputMsgType> createReadNativeTypesResponse(ReadNativeTypesOutputMsgType value) {
        return new JAXBElement<ReadNativeTypesOutputMsgType>(_ReadNativeTypesResponse_QNAME, ReadNativeTypesOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadDomainsOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadDomainsResponse")
    public JAXBElement<ReadDomainsOutputMsgType> createReadDomainsResponse(ReadDomainsOutputMsgType value) {
        return new JAXBElement<ReadDomainsOutputMsgType>(_ReadDomainsResponse_QNAME, ReadDomainsOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusteringSummaryOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClusteringSummaryResponse")
    public JAXBElement<GetClusteringSummaryOutputMsgType> createGetClusteringSummaryResponse(GetClusteringSummaryOutputMsgType value) {
        return new JAXBElement<GetClusteringSummaryOutputMsgType>(_GetClusteringSummaryResponse_QNAME, GetClusteringSummaryOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WriteUserOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "WriteUserResponse")
    public JAXBElement<WriteUserOutputMsgType> createWriteUserResponse(WriteUserOutputMsgType value) {
        return new JAXBElement<WriteUserOutputMsgType>(_WriteUserResponse_QNAME, WriteUserOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessDataOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetProcessDataResponse")
    public JAXBElement<GetProcessDataOutputMsgType> createGetProcessDataResponse(GetProcessDataOutputMsgType value) {
        return new JAXBElement<GetProcessDataOutputMsgType>(_GetProcessDataResponse_QNAME, GetProcessDataOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProcessOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "UpdateProcessResponse")
    public JAXBElement<UpdateProcessOutputMsgType> createUpdateProcessResponse(UpdateProcessOutputMsgType value) {
        return new JAXBElement<UpdateProcessOutputMsgType>(_UpdateProcessResponse_QNAME, UpdateProcessOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadNativeTypesInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadNativeTypesRequest")
    public JAXBElement<ReadNativeTypesInputMsgType> createReadNativeTypesRequest(ReadNativeTypesInputMsgType value) {
        return new JAXBElement<ReadNativeTypesInputMsgType>(_ReadNativeTypesRequest_QNAME, ReadNativeTypesInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WriteAnnotationOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "WriteAnnotationResponse")
    public JAXBElement<WriteAnnotationOutputMsgType> createWriteAnnotationResponse(WriteAnnotationOutputMsgType value) {
        return new JAXBElement<WriteAnnotationOutputMsgType>(_WriteAnnotationResponse_QNAME, WriteAnnotationOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProcessInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "UpdateProcessRequest")
    public JAXBElement<UpdateProcessInputMsgType> createUpdateProcessRequest(UpdateProcessInputMsgType value) {
        return new JAXBElement<UpdateProcessInputMsgType>(_UpdateProcessRequest_QNAME, UpdateProcessInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateClustersInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "CreateClustersRequest")
    public JAXBElement<CreateClustersInputMsgType> createCreateClustersRequest(CreateClustersInputMsgType value) {
        return new JAXBElement<CreateClustersInputMsgType>(_CreateClustersRequest_QNAME, CreateClustersInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadUserInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "ReadUserRequest")
    public JAXBElement<ReadUserInputMsgType> createReadUserRequest(ReadUserInputMsgType value) {
        return new JAXBElement<ReadUserInputMsgType>(_ReadUserRequest_QNAME, ReadUserInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusterSummariesInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "GetClusterSummariesRequest")
    public JAXBElement<GetClusterSummariesInputMsgType> createGetClusterSummariesRequest(GetClusterSummariesInputMsgType value) {
        return new JAXBElement<GetClusterSummariesInputMsgType>(_GetClusterSummariesRequest_QNAME, GetClusterSummariesInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteEditSessionOutputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "DeleteEditSessionResponse")
    public JAXBElement<DeleteEditSessionOutputMsgType> createDeleteEditSessionResponse(DeleteEditSessionOutputMsgType value) {
        return new JAXBElement<DeleteEditSessionOutputMsgType>(_DeleteEditSessionResponse_QNAME, DeleteEditSessionOutputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditProcessDataInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "EditProcessDataRequest")
    public JAXBElement<EditProcessDataInputMsgType> createEditProcessDataRequest(EditProcessDataInputMsgType value) {
        return new JAXBElement<EditProcessDataInputMsgType>(_EditProcessDataRequest_QNAME, EditProcessDataInputMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPairwiseDistancesInputMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:qut-edu-au:schema:apromore:manager", name = "PairwiseDistancesRequest")
    public JAXBElement<GetPairwiseDistancesInputMsgType> createPairwiseDistancesRequest(GetPairwiseDistancesInputMsgType value) {
        return new JAXBElement<GetPairwiseDistancesInputMsgType>(_PairwiseDistancesRequest_QNAME, GetPairwiseDistancesInputMsgType.class, null, value);
    }

}
