//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 04:10:32 PM EST 
//


package org.apromore.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for PiarDistanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PiarDistanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FragmentId1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FragmentId2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PiarDistanceType", propOrder = {
    "fragmentId1",
    "fragmentId2",
    "distance"
})
public class PiarDistanceType
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "FragmentId1", required = true)
    protected String fragmentId1;
    @XmlElement(name = "FragmentId2", required = true)
    protected String fragmentId2;
    @XmlElement(name = "Distance")
    protected double distance;

    /**
     * Gets the value of the fragmentId1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentId1() {
        return fragmentId1;
    }

    /**
     * Sets the value of the fragmentId1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentId1(String value) {
        this.fragmentId1 = value;
    }

    /**
     * Gets the value of the fragmentId2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentId2() {
        return fragmentId2;
    }

    /**
     * Sets the value of the fragmentId2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentId2(String value) {
        this.fragmentId2 = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public double getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(double value) {
        this.distance = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theFragmentId1;
            theFragmentId1 = this.getFragmentId1();
            strategy.appendField(locator, this, "fragmentId1", buffer, theFragmentId1);
        }
        {
            String theFragmentId2;
            theFragmentId2 = this.getFragmentId2();
            strategy.appendField(locator, this, "fragmentId2", buffer, theFragmentId2);
        }
        {
            double theDistance;
            theDistance = this.getDistance();
            strategy.appendField(locator, this, "distance", buffer, theDistance);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PiarDistanceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PiarDistanceType that = ((PiarDistanceType) object);
        {
            String lhsFragmentId1;
            lhsFragmentId1 = this.getFragmentId1();
            String rhsFragmentId1;
            rhsFragmentId1 = that.getFragmentId1();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fragmentId1", lhsFragmentId1), LocatorUtils.property(thatLocator, "fragmentId1", rhsFragmentId1), lhsFragmentId1, rhsFragmentId1)) {
                return false;
            }
        }
        {
            String lhsFragmentId2;
            lhsFragmentId2 = this.getFragmentId2();
            String rhsFragmentId2;
            rhsFragmentId2 = that.getFragmentId2();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fragmentId2", lhsFragmentId2), LocatorUtils.property(thatLocator, "fragmentId2", rhsFragmentId2), lhsFragmentId2, rhsFragmentId2)) {
                return false;
            }
        }
        {
            double lhsDistance;
            lhsDistance = this.getDistance();
            double rhsDistance;
            rhsDistance = that.getDistance();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "distance", lhsDistance), LocatorUtils.property(thatLocator, "distance", rhsDistance), lhsDistance, rhsDistance)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theFragmentId1;
            theFragmentId1 = this.getFragmentId1();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fragmentId1", theFragmentId1), currentHashCode, theFragmentId1);
        }
        {
            String theFragmentId2;
            theFragmentId2 = this.getFragmentId2();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fragmentId2", theFragmentId2), currentHashCode, theFragmentId2);
        }
        {
            double theDistance;
            theDistance = this.getDistance();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "distance", theDistance), currentHashCode, theDistance);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
