//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 04:10:32 PM EST 
//


package org.apromore.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ReadProcessSummaryInputMsgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReadProcessSummaryInputMsgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessVersions" type="{urn:qut-edu-au:schema:apromore:manager}ProcessVersionsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReadProcessSummaryInputMsgType", propOrder = {
    "processVersions"
})
public class ReadProcessSummaryInputMsgType
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "ProcessVersions", required = true)
    protected ProcessVersionsType processVersions;

    /**
     * Gets the value of the processVersions property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessVersionsType }
     *     
     */
    public ProcessVersionsType getProcessVersions() {
        return processVersions;
    }

    /**
     * Sets the value of the processVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessVersionsType }
     *     
     */
    public void setProcessVersions(ProcessVersionsType value) {
        this.processVersions = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            ProcessVersionsType theProcessVersions;
            theProcessVersions = this.getProcessVersions();
            strategy.appendField(locator, this, "processVersions", buffer, theProcessVersions);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ReadProcessSummaryInputMsgType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ReadProcessSummaryInputMsgType that = ((ReadProcessSummaryInputMsgType) object);
        {
            ProcessVersionsType lhsProcessVersions;
            lhsProcessVersions = this.getProcessVersions();
            ProcessVersionsType rhsProcessVersions;
            rhsProcessVersions = that.getProcessVersions();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "processVersions", lhsProcessVersions), LocatorUtils.property(thatLocator, "processVersions", rhsProcessVersions), lhsProcessVersions, rhsProcessVersions)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            ProcessVersionsType theProcessVersions;
            theProcessVersions = this.getProcessVersions();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "processVersions", theProcessVersions), currentHashCode, theProcessVersions);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
